apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-namespace
  namespace: exercises
spec:
  metrics:
    - name: total-cpu-usage
      initialDelay: 30s
      interval: 30s
      count: 10
      failureCondition: result > 0.8
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1755-prometheus.prometheus.svc.cluster.local:9090
          query: |
            sum(
              rate(container_cpu_usage_seconds_total{namespace="exercises",container!=""}[5m])
            )
---

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ping-pong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause:
            duration: 30s
        - analysis:
            templates:
              - templateName: cpu-usage-namespace
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: march787/ping-pong:v7
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: POSTGRES_HOST
              value: "postgres-svc"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "postgres"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: http