apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: exercises
spec:
  type: LoadBalancer
  selector:
    app: log-output
  ports:
    - port: 1234
      protocol: TCP
      targetPort: 3000

