apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-db-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: pg-backup
              image: google/cloud-sdk:latest
              env:
                - name: PGHOST
                  value: postgres-svc
                - name: PGUSER
                  value: postgres
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
                - name: BUCKET_NAME
                  value: todo-project
                - name: DB_NAME
                  value: postgres
              volumeMounts:
                - name: gcp-key
                  mountPath: /secrets
                  readOnly: true
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  export GOOGLE_APPLICATION_CREDENTIALS="/secrets/key.json"

                  gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"
                  gcloud config set project dwk-gke-468414

                  apt-get update -y
                  apt-get install -y --no-install-recommends postgresql-client
                  rm -rf /var/lib/apt/lists/*

                  TS="$(date +%Y-%m-%d_%H-%M-%S)"
                  BACKUP_FILE="todo-${TS}.sql.gz"

                  pg_dump -U "$PGUSER" -h "$PGHOST" "$DB_NAME" | gzip > "$BACKUP_FILE"

                  gsutil cp "$BACKUP_FILE" "gs://${BUCKET_NAME}/$BACKUP_FILE"
          volumes:
            - name: gcp-key
              secret:
                secretName: gcp-sa-key
