apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-deployment
spec:
  template:
    spec:
      containers:
      - name: broadcaster
        env:
          - name: ENV
            value: "production"
        envFrom:
        - secretRef:
            name: telegram-credentials
