
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-deployment
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:latest
        ports:
        - containerPort: 4222
        - containerPort: 8222

---

apiVersion: v1
kind: Service
metadata:
  name: nats-service
  namespace: project
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222